### PR TITLE
Transform arrow functions without block

### LINKED ISSUE #101: Generated JS code behaves differently from original source code
**Describe what happened:**

Code generated by `Rewriter.rewrite` function presents a different behavior than the original source code.

**Describe what you expected:**

Code generated by the `Rewriter.rewrite` function to behave the same as the original source code.

**Steps to reproduce the issue:**

When using the same csi methods used by [dd-trace-js/dd-trace/src/appsec/iast/taint-tracking](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js):

```js
  csiMethods: [
    {src: 'concat'},
    {src: 'join'},
    {src: 'parse'},
    {src: 'plusOperator', operator: true},
    {src: 'random'},
    {src: 'replace'},
    {src: 'slice'},
    {src: 'substr'},
    {src: 'substring'},
    {src: 'toLowerCase', dst: 'stringCase'},
    {src: 'toUpperCase', dst: 'stringCase'},
    {src: 'tplOperator', operator: true},
    {src: 'trim'},
    {src: 'trimEnd'},
    {src: 'trimStart', dst: 'trim'},
    {src: 'eval', allowedWithoutCallee: true}
  ]
```

The following input code:

```js
"use strict";

function names(arg) {
  const flag = arg;
  const addPrefix = (value) => (flag ? `"${value}"` : `"my_prefix.${value}"`);
  const result = `
      ${addPrefix('NAME_0')}
      ${addPrefix('NAME_1')}
      ${addPrefix('NAME_2')}
      ${addPrefix('NAME_3')}
    `;
  return result;
}

console.log(names(false))
```

Which outputs this:

```
      "my_prefix.NAME_0"
      "my_prefix.NAME_1"
      "my_prefix.NAME_2"
      "my_prefix.NAME_3"
```

Here the generated code, using `Rewriter.rewrite`:

```js
"use strict";
function names(arg) {
    let __datadog_rkfexd_0, __datadog_rkfexd_1, __datadog_rkfexd_2, __datadog_rkfexd_3;
    const flag = arg;
    const addPrefix = (value)=>(flag ? (__datadog_rkfexd_0 = value, _ddiast.tplOperator(`"${__datadog_rkfexd_0}"`, __datadog_rkfexd_0)) : (__datadog_rkfexd_0 = value, _ddiast.tplOperator(`"my_prefix.${__datadog_rkfexd_0}"`, __datadog_rkfexd_0)));
    const result = (__datadog_rkfexd_0 = addPrefix('NAME_0'), __datadog_rkfexd_1 = addPrefix('NAME_1'), __datadog_rkfexd_2 = addPrefix('NAME_2'), __datadog_rkfexd_3 = addPrefix('NAME_3'), _ddiast.tplOperator(`
      ${__datadog_rkfexd_0}
      ${__datadog_rkfexd_1}
      ${__datadog_rkfexd_2}
      ${__datadog_rkfexd_3}
    `, __datadog_rkfexd_0, __datadog_rkfexd_1, __datadog_rkfexd_2, __datadog_rkfexd_3));
    return result;
}
console.log(names(false));
```

Which outputs this instead:

```
      NAME_3
      "my_prefix.NAME_1"
      "my_prefix.NAME_2"
      "my_prefix.NAME_3"
```

Here's a [repository](https://github.com/tprado/datadog-iast-rewriter-issue) that demonstrates the issue.

**Additional environment details (language runtime version, list of relevant dependencies and versions, operating System, cloud provider, etc):**

- node v20.18.0
- @datadog/native-iast-rewriter v2.5.0

### PR DESCRIPTION
**Pull request by iunanua**
### What does this PR do?

Transform arrow function bodies with a expression to a body with a block returning the original expression.

### Motivation

Fix #101 

### Checklist

- [ ] The CHANGELOG.md has been updated
- [ ] Unit tests have been updated and pass
- [ ] If known, an appropriate milestone has been selected

### CODE REVIEW

File: test/resources/issue-101.js [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+  const addPrefix = (value) => (flag ? `"${value}"` : `"my_prefix.${addSufix(value)}"`)
+  const result = `
+      ${addPrefix('NAME_0')}
+      ${addPrefix('NAME_1')}
+      ${addPrefix('NAME_2')}
+      ${addPrefix('NAME_3')}
+    `
+  return result
+}
+
```
Comment (uurien) [inline test/resources/issue-101.js:41]: Could you try to do also these tests:

```suggestion

function namesDoubleResult(arg) {
  const flag = arg
  const addPrefix = (value) => (flag ? `"${value}"` : `"my_prefix.${value}"`)
  const resultFake = `
      ${addPrefix('NAME_0')}
      ${addPrefix('NAME_1')}
      ${addPrefix('NAME_2')}
      ${addPrefix('NAME_3')}
    `
  const result = `
      ${addPrefix('NAME_0')}
      ${addPrefix('NAME_1')}
      ${addPrefix('NAME_2')}
      ${addPrefix('NAME_3')}
    `
  return result
}

function namesNoFlag() {
  const addPrefix = (value) => `"my_prefix.${value}"`
  const result = `
      ${addPrefix('NAME_0')}
      ${addPrefix('NAME_1')}
      ${addPrefix('NAME_2')}
      ${addPrefix('NAME_3')}
    `
  return result
}

function namesNoFlagDoubleResult() {
  const addPrefix = (value) => `"my_prefix.${value}"`
  const resultFake = `
      ${addPrefix('NAME_0')}
      ${addPrefix('NAME_1')}
      ${addPrefix('NAME_2')}
      ${addPrefix('NAME_3')}
    `
  const result = `
      ${addPrefix('NAME_0')}
      ${addPrefix('NAME_1')}
      ${addPrefix('NAME_2')}
      ${addPrefix('NAME_3')}
    `
  return result
}
```

File: test/resources/issue-101.js [hunk 2]
```diff
@@ -0,0 +1,112 @@
+'use strict'
+
+function names(arg) {
```
Comment (uurien) [inline test/resources/issue-101.js:3]: For all the methods (why is not failing the linter?)
```suggestion
function names (arg) {
```

File: src/visitor/operation_transform_visitor.rs [hunk 3]
```diff
@@ -162,6 +163,14 @@ impl VisitMut for OperationTransformVisitor<'_> {
                 }
             }
 
+            Expr::Arrow(arrow) => {
+                let transform_result = ArrowTransform::to_dd_arrow_expr(arrow);
+                if transform_result.is_modified() {
+                    expr.map_with_mut(|e| transform_result.expr.unwrap_or(e));
+                    // do not update status yet
+                }
```
Comment (uurien) [inline src/visitor/operation_transform_visitor.rs:171]: why aren't we calling to the visitor with the children?

I miss some test checking that things like:
```
() => `a.b${c}`
() => {
    res = 'a.b' + c
}
...
```
are rewritten as expected.

Comment (uurien) [reply src/visitor/operation_transform_visitor.rs:171]: ok got it, we don't need to call to the children here, because we are creating new block, and it is `block_transform_visitor` which will visit the new block

File: test/resources/issue-101.js (hunk 2 above)
Comment (iunanua) [reply test/resources/issue-101.js:3]: `test/resources` is [ignored](https://github.com/DataDog/dd-native-iast-rewriter-js/blob/main/.eslintignore#L2)  

But i'm going to rename the methods

File: src/tests/arrow_func_tests.rs [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+                .transform_status
+                .is_some_and(|status| status.status == Status::NotModified),
+        );
+
+        Ok(())
+    }
+
+    #[test]
+    fn test_arrow_modified() -> Result<(), String> {
+        let original_code = "{const a = (arg) => arg ? `hello ${arg}` : '' }".to_string();
```
[the remark this answers is not in the document]
Comment (iunanua) [reply src/tests/arrow_func_tests.rs:89]: done

File: src/visitor/operation_transform_visitor.rs (hunk 3 above)
Comment (iunanua) [reply src/visitor/operation_transform_visitor.rs:171]: `BlockTransformVisitor` is visiting the arrow body block after mutating the arrow expression

File: src/tests/arrow_func_tests.rs [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+        .to_string();
+        let js_file = "test.js".to_string();
+        let rewritten = rewrite_js(original_code, js_file).map_err(|e| e.to_string())?;
+
+        assert_that(
+            &rewritten
+                .transform_status
+                .is_some_and(|status| status.status == Status::Modified),
+        );
+        assert_that(&rewritten.code).contains("const a = (arg)=>{
```
Comment (uurien) [inline src/tests/arrow_func_tests.rs:121]: `let let __datadog_test_0` should be defined twice, in and out of lambda, without it, the one that is used in `const b` is not defined. 
```suggestion
        assert_that(&rewritten.code).contains("let __datadog_test_0
const a = (arg)=>{

Comment (iunanua) [reply src/tests/arrow_func_tests.rs]: i wanted to test that __datadog_test_0 was defined inside the arrow but I changed the assertion to include also __datadog_test_0 from outside

File: test/resources/issue-101.js (hunk 2 above)
Comment (iunanua) [reply test/resources/issue-101.js]: done

**Review by uurien — APPROVED** [review]
